export const LOAD_SURFACE_SERVERS_SUCCESS = "LOAD_SURFACE_SERVERS_SUCCESS";

export const UPDATE_FILTERED_SURFACES = "UPDATE_FILTERED_SURFACES";
export const UPDATE_FILTERED_SERVERS = "UPDATE_FILTERED_SERVERS";

export const UPDATE_SELECTED_SURFACE = "UPDATE_SELECTED_SURFACE";
export const UPDATE_EXTRACTED_SERVER = "UPDATE_EXTRACTED_SERVER";
export const UPDATE_SEARCH_TERM = "UPDATE_SEARCH_TERM";

export const API_CALL_BEGIN = "API_CALL_BEGIN";
export const API_CALL_ERROR = "API_CALL_ERROR";
